name: calendar_views_example
version: 0.6.0
description: Examples of calendar_views library.

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  calendar_views:
    path: ../

dev_dependencies:


flutter:
  uses-material-design: true
