name: calendar_views
version: 0.6.0

description: Collection of customisable calendar related widgets for Flutter.

author: ZedTheLed<zedtheled@gmail.com>

homepage: https://github.com/ZedTheLed/calendar_views
documentation:

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  quiver: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.16.1 <3.0.0'
